name: hexlet-action
on: [push]
jobs:
  linter-test:
    runs-on: ubuntu-latest
    steps:
      - name: linter-check
        run:
                pip install poetry
                make lint
           


